version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-cli: circleci/aws-cli@3.1.1

executors:
  client:
    resource_class: small
    working_directory: ~/packages/client
    docker:
      - image: node:16-alpine3.15

parameters:
  build_and_push_s3:
    type: boolean
    default: false

  build_and_push_ecr:
    type: boolean
    default: false

jobs:
  build_client:
    executor: client
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build Project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_client:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-region: $AWS_REGION
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      - run:
          name: Upload to S3
          command: aws s3 sync ./build/ s3://$S3_BUCKET --delete

workflows:
  version: 2
  build_and_push_s3:
    when: << pipeline.parameters.build_and_push_s3 >>
    jobs:
      - build_client:
          context: zekia
          filters:
            branches:
              only: main

      - deploy_client:
          context: zekia
          requires:
            - build_client
          filters:
            branches:
              only: main

  build_and_push_ecr:
    when: << pipeline.parameters.build_and_push_ecr >>
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY

          context: zekia
          executor: aws-ecr/default

          extra-build-args: "--compress"
          no-output-timeout: 20m
          path: ./packages/api/Dockerfile
          platform: linux/amd64
          profile-name: circleci
          public-registry: false

          region: $AWS_REGION
          registry-id: $AWS_ACCOUNT_ID
          repo: $ECR_REPO_NAME
          repo-scan-on-push: true
          skip-when-tags-exist: false
